reg delete "HKEY_CLASSES_ROOT\Directory\Background\shell\cmd"
reg delete "HKEY_CLASSES_ROOT\Directory\Background\shell\Powershell"
reg delete "HKEY_CLASSES_ROOT\Directory\Background\shell\WSL"
reg delete "HKEY_CLASSES_ROOT\Directory\Background\shell\AnyCode"
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked"
reg delete "HKEY_CLASSES_ROOT\Directory\background\shell\git_gui"
reg delete "HKEY_CLASSES_ROOT\Directory\background\shell\git_shell"
reg delete "HKEY_CLASSES_ROOT\Directory\Shell\git_gui"
reg delete "HKEY_CLASSES_ROOT\Directory\Shell\git_shell"
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shell\git_gui"
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shell\git_shell"
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shell\git_gui"
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shell\git_shell"
